FROM nodered/node-red
RUN npm install node-red-dashboard \
    npm install node-red-contrib-blynk-ws \
    npm install node-red-contrib-influxdb \
    npm install node-red-contrib-schedex \
    npm install node-red-contrib-telegrambot \
    npm install node-red-contrib-power-monitor \
    npm install node-red-contrib-timeout \
    npm install node-red-contrib-ttn \
    npm install node-red-contrib-yield \
    mpm install node-red-node-pushover
